// SPDX-License-Identifier: MIT
pragma solidity 0.8.35;

error ZeroAddressError();
error InvalidAmountError();
error InvalidFeeError();
error InvalidBasisPointsError();
error InvalidTokenError();
error InvalidDecimalsError();
error InvalidApprovalError();
error InvalidOfferDirectionError();
error InvalidFlowQuoterError();
error TakeOfferDeadlineExpiredError(uint64 deadline);
error MinimumAmountOutNotMetError(uint256 minimumAmountOut, uint256 actualAmountOut);
error WorkerOfferRequiresFulfillmentRequestError(bytes32 offerConfigId);
error KilledError();
error ExactAssetTransferRequiredError(address asset, uint256 expectedAmount, uint256 receivedAmount);
error ExactAssetDebitRequiredError(address asset, uint256 expectedAmount, uint256 debitedAmount);
error ExcludedSupplyAddressAlreadyExistsError(address onReToken, address account);
error ExcludedSupplyAddressNotFoundError(address onReToken, address account);
error TooManyExcludedSupplyAddressesError(address onReToken);
error TokenNotRegisteredError(address onReToken);
error TokenAlreadyRegisteredError(address onReToken);
error PricerAlreadyExistsError(bytes32 pricerId);
error PricerNotFoundError(bytes32 pricerId);
error PricerDisabledError(bytes32 pricerId);
error QuoterAlreadyExistsError(bytes32 quoterId);
error QuoterNotFoundError(bytes32 quoterId);
error QuoterDisabledError(bytes32 quoterId);
error PropRfqConfigurationRequiredError();
error InvalidQuoterKindError(bytes32 quoterId, uint8 expectedKind, uint8 actualKind);
error InvalidPropRfqPairError(bytes32 quoterId, address tokenIn, address tokenOut);
error FeeConfigAlreadyExistsError(bytes32 feeConfigId);
error FeeConfigNotFoundError(bytes32 feeConfigId);
error FeeConfigDisabledError(bytes32 feeConfigId);
error ConfigurableVaultAlreadyExistsError(bytes32 vaultId);
error ConfigurableVaultNotFoundError(bytes32 vaultId);
error InvalidConfigurableVaultKindError(bytes32 vaultId, uint8 expectedKind, uint8 actualKind);
error MissingConfigurableVaultDestinationError(bytes32 vaultId);
error OfferConfigAlreadyExistsError(bytes32 offerConfigId);
error OfferConfigNotFoundError(bytes32 offerConfigId);
error OfferConfigDisabledError(bytes32 offerConfigId);
error FulfillmentRequestAlreadyExistsError(bytes32 fulfillmentRequestId);
error FulfillmentRequestNotFoundError(bytes32 fulfillmentRequestId);
error FulfillmentAmountExceedsRemainingError(bytes32 fulfillmentRequestId, uint256 amount, uint256 remaining);
error LiquidityVaultRequiredError(bytes32 offerConfigId);
error InsufficientLiquidityError(bytes32 vaultId, address token, uint256 availableAmount, uint256 requiredAmount);
error ZeroBalanceError();
error InsufficientBalanceError(uint256 availableAmount, uint256 requestedAmount);
error UnauthorizedError(address sender);
error UnsupportedRoleError(bytes32 role);
error BossRoleManagedSeparatelyError();
error NotPendingBossError(address account);
error BothApproversFilledError();
error ApproverAlreadyExistsError(address approver);
error NotApproverError(address approver);
error NoChangeError();
error TooManyVectorsError();
error DuplicateVectorStartTimeError(uint64 startTime);
error InvalidVectorOrderError();
error VectorBaseTimeAfterStartTimeError(uint64 baseTime, uint64 startTime);
error VectorStartTimeInPastError(uint64 startTime, uint64 currentTime);
error VectorNotFoundError(uint64 startTime);
error VectorIndexOutOfBoundsError(uint8 vectorIndex, uint8 vectorCount);
error NoActiveVectorError(bytes32 pricerId);
