// SPDX-License-Identifier: __SOLC_SPDX__
pragma solidity >=__SOLC_VERSION__;

/// ------------------------------------------------------------------------------------------------------------
///
/// NOTE: This file is auto-generated by Gemforge from `templates/DiamondProxy.sol`.
///
/// It replaces Gemforge's stock template because the OnRe Diamond is not ERC-173
/// owner-gated: `diamondCut` is gated on `LibOnReRoles.UPGRADER_ROLE`, so there is
/// no `OwnershipFacet` to install and no `contractOwner` slot to seed.
///
/// ------------------------------------------------------------------------------------------------------------

import { Diamond } from '__LIB_DIAMOND_PATH__/contracts/Diamond.sol';
import { LibDiamond } from '__LIB_DIAMOND_PATH__/contracts/libraries/LibDiamond.sol';
import { DiamondCutFacet } from '__LIB_DIAMOND_PATH__/contracts/facets/DiamondCutFacet.sol';
import { DiamondLoupeFacet } from '__LIB_DIAMOND_PATH__/contracts/facets/DiamondLoupeFacet.sol';
import { IDiamondCut } from '__LIB_DIAMOND_PATH__/contracts/interfaces/IDiamondCut.sol';
import { IDiamondLoupe } from '__LIB_DIAMOND_PATH__/contracts/interfaces/IDiamondLoupe.sol';
import { IERC165 } from '__LIB_DIAMOND_PATH__/contracts/interfaces/IERC165.sol';
import { LibOnReAccessControl } from '../libraries/LibOnReAccessControl.sol';
import { LibOnReRoles } from '../libraries/LibOnReRoles.sol';

contract DiamondProxy is Diamond {
  error BootstrapUpgraderIsZero();

  /// @param bootstrapUpgrader Address allowed to sign the first `diamondCut`.
  /// Gemforge passes the deployment wallet here, then immediately calls
  /// `diamondCut` with the application facets and `OnReDiamondInit.init`.
  /// `init` revokes this grant once the configured upgrader holds the role, so
  /// the authority is transient — see `OnReDiamondInit._handOffBootstrapUpgrader`.
  constructor(address bootstrapUpgrader) payable {
    if (bootstrapUpgrader == address(0)) {
      revert BootstrapUpgraderIsZero();
    }
    LibOnReAccessControl._grantRoleUnchecked(LibOnReRoles.UPGRADER_ROLE, bootstrapUpgrader);

    _initCoreFacets();

    // Only the standard, immutable interfaces are advertised here. The
    // application-level ids are registered by `OnReDiamondInit.init`.
    LibDiamond.DiamondStorage storage ds = LibDiamond._diamondStorage();
    ds.supportedInterfaces[type(IERC165).interfaceId] = true;
    ds.supportedInterfaces[type(IDiamondCut).interfaceId] = true;
    ds.supportedInterfaces[type(IDiamondLoupe).interfaceId] = true;
  }

  // Internal

  function _initCoreFacets() private {
    IDiamondCut.FacetCut[] memory cut = new IDiamondCut.FacetCut[](2);

    bytes4[] memory f0 = new bytes4[](1);
    f0[0] = IDiamondCut.diamondCut.selector;
    cut[0] = IDiamondCut.FacetCut({
      facetAddress: address(new DiamondCutFacet()),
      action: IDiamondCut.FacetCutAction.Add,
      functionSelectors: f0
    });

    bytes4[] memory f1 = new bytes4[](5);
    f1[0] = IDiamondLoupe.facets.selector;
    f1[1] = IDiamondLoupe.facetFunctionSelectors.selector;
    f1[2] = IDiamondLoupe.facetAddresses.selector;
    f1[3] = IDiamondLoupe.facetAddress.selector;
    f1[4] = IERC165.supportsInterface.selector;
    cut[1] = IDiamondCut.FacetCut({
      facetAddress: address(new DiamondLoupeFacet()),
      action: IDiamondCut.FacetCutAction.Add,
      functionSelectors: f1
    });

    LibDiamond._diamondCut(cut, address(0), "");
  }
}
